apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  labels:
    component: backend
spec:
  containers:
    - name: backend
      image: task-mgt-be
      ports:
        - containerPort: 4000
          name: port-svc
          protocol: TCP
